### ISSUE TITLE
ROS2 Topics Don't Show Up

### ISSUE THREAD

**Issue by GeorgeNegret** [AndrejOrsula/space_robotics_bench#14]
Hi Andrej,

Thank you for sharing your amazing work !

![Screenshot from 2024-11-21 18-16-26](https://github.com/user-attachments/assets/079e97a4-7c66-49a1-b4b1-6e9cf1e24cdf)

I tried ROS2 workflow but I can't view the ros2 topics.

[ros2.py --env ingenuity.log](https://github.com/user-attachments/files/17849509/ros2.py.--env.ingenuity.log)

**Comment by AndrejOrsula** [comment]
Hello George,

Thank you for opening this issue!

I just did a quick test on `main` with a fresh build, and it seems to work:

```bash
# T1
space_robotics_bench/.docker/run.bash ros2 run space_robotics_bench ros2.py --env ingenuity
```

```bash
# T2
space_robotics_bench/.docker/join.bash
[TRACE] docker exec --interactive --tty space_robotics_bench bash
# T2 inside container
root@host:~/ws# ros2 topic list
1732216167.005859 [0]       ros2: selected interface "lo" is not multicast-capable: disabling multicast
/clock
/env0/reward
/env0/robot/cmd_vel
/env0/terminated
/env0/truncated
/envs/info
/envs/robot/cmd_vel
/parameter_events
/rosout
/tf
```

Therefore, I suspect the issue might be with the ROS 2 middleware communication. Here are some things I would suggest you to try:

1) **Run `ros2 topic echo` from a local installation of ROS 2 or even from a different machine on the same subnet (remember to set `ROS_DOMAIN_ID` to be the same in both the container and outside).**

2) **Change `ROS_DOMAIN_ID` and restrict communication to localhost:** 

```bash
# T1
ROS_DOMAIN_ID=42 ROS_LOCALHOST_ONLY=1 space_robotics_bench/.docker/run.bash ros2 run space_robotics_bench ros2.py --env ingenuity
```

```bash
# T2
space_robotics_bench/.docker/join.bash
# T2 inside container
ros2 topic list
```

3) **Try with `RMW_IMPLEMENTATION=rmw_fastrtps_cpp` (requires installation because CycloneDDS is used by default)**

```bash
# T1
RMW_IMPLEMENTATION=rmw_fastrtps_cpp ~/ws/code/space_robotics_bench/.docker/run.bash
# T1 inside container
apt update && apt install -y ros-humble-rmw-fastrtps-cpp
ros2 run space_robotics_bench ros2.py --env ingenuity
```

```bash
# T2
space_robotics_bench/.docker/join.bash
# T2 inside container
ros2 topic list
```

If this still doesn't work, feel free to let me know. You could also try to reconfigure CycloneDDS via `CYCLONEDDS_URI` but I'm unsure if it would help.

---


<details><summary>Details about missing observations (click to expand) </summary>

Proprioceptive observations and ground truth are currently disabled on `main` due to prior optimization changes for RL workflows. I will work towards exposing all observations and reward components in the coming weeks.

For now, only image observations for `*_visual` environments are exposed via ROS 2 topics. You can enable 2/3 RGB-D cameras per environment by using such environment variants, e.g. `--env ingenuity_visual.` Here are the topics that should appear for the Ingenuity demo:

```bash
/env0/camera_scene/depth/image_raw
/env0/camera_scene/image_raw
/env0/robot/camera_bottom/depth/image_raw
/env0/robot/camera_bottom/image_raw
```

</details>

**Comment by GeorgeNegret** [comment]
Thanks ! Works with settings ROS_DOMAIN_ID=42 ROS_LOCALHOST_ONLY=1

**Comment by AndrejOrsula** [comment]
Okay, great!

I just realized that `--env ROS_LOCALHOST_ONLY=0` is set in your logs, so `ROS_LOCALHOST_ONLY=0` gets propagated from your system (which is done on purpose). Therefore, the origin of the issue is most likely from CycloneDDS selecting some network interface (wifi/eth/...) that is somehow unsuitable for the current setup. Therefore, setting `ROS_DOMAIN_ID=42` is probably not necessary.

I will investigate a way to automatically reconfigure CycloneDDS to use all interfaces when subnet discovery is enabled (or just default to `RMW_IMPLEMENTATION=rmw_fastrtps_cpp`).

Thank you again for opening the issue.

**Comment by GeorgeNegret** [comment]
Hi @AndrejOrsula 
[wheelbot.zip](https://github.com/user-attachments/files/17872431/wheelbot.zip)
,
I would like to add a ROS2 mobile robot with the configuration in the attached file, do you think it is achievable?

**Comment by AndrejOrsula** [comment]
Hello @GeorgeNegret,

Yes, it should be feasible to add the wheeled robot. The closest integrated robot is currently the Perseverance rover with [USD file here](https://github.com/AndrejOrsula/srb_assets/blob/ecf96c25b94c0d4cf2daeb67c2a9f5bc5afe5242/model/robot/perseverance/perseverance.usdc) and [Python config here](https://github.com/AndrejOrsula/space_robotics_bench/blob/1b309d3d8540ddccb14029287c34b9be3030b36a/space_robotics_bench/assets/robot/perseverance.py).

Currently, there is no specific controller for differential drive/skid-steer, but that should be relatively simple to add based on the existing [rocker-boogie/Ackermann rover drive](https://github.com/AndrejOrsula/space_robotics_bench/blob/1b309d3d8540ddccb14029287c34b9be3030b36a/space_robotics_bench/core/actions/mobile.py#L13). It might also be just possible to use one from Isaac Sim/Lab.

The time-consuming part can be configuring the USD with the joints and appropriate APIs (collider, rigid body, drives). For the Perseverance, I did it manually inside Omniverse - and I think that might be the most straightforward approach right now, as you can use the other models as a "template" by introspecting their APIs. Furthermore, there are a number of Omniverse/Isaac Sim tutorials and resources that are directly applicable. Eventually, I would like to add a more programmatic/automated approach for defining parametric robots, but that is currently not my priority.

**Comment by GeorgeNegret** [comment]
Hi @AndrejOrsula ,
Thank you very much for the details !
